################################################################
# Global configuration
################################################################

logLevel = "ERROR"
defaultEntryPoints = ["http", "https"]

#[accessLog]

################################################################
# Entrypoints configuration
################################################################

# Entrypoints definition
#
# Optional
# Default:
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
    [[entryPoints.https.tls.certificates]]
      certFile = "/certs/server.crt"
      keyFile = "/certs/server.key"
# Enable API and dashboard
[api]
entryPoint = "traefik"
dashboard = true

################################################################
# Ping configuration
################################################################

# Enable ping
[ping]

  # Name of the related entry point
  #
  # Optional
  # Default: "traefik"
  #
  # entryPoint = "traefik"

################################################################
# Docker configuration backend
################################################################

# Enable Docker configuration backend
[docker]
endpoint = "unix:///var/run/docker.sock"
exposedbydefault = false
watch = true

#[acme]
#email = "kai.letsencrypt@gmail.com"
#storage = "/etc/traefik/acme/acme.json"
#entryPoint = "https"
#onHostRule = true
#[acme.httpChallenge]
#entryPoint = "http"
