networks:
  webgateway: {driver: bridge}
services:
  dnsmasq:
    container_name: dnsmasq
    environment: [HTTP_USER=kelghar, HTTP_PASS=Bigfoot]
    image: jpillora/dnsmasq:latest
    network_mode: host
    ports: ['5380:5380', '53:53/udp', '67:67/udp']
    privileged: true
    volumes: ['${DOCKER_CONFIG}/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf', '${DOCKER_CONFIG}/dnsmasq/hosts:/etc/hosts']
  ffsync:
    container_name: ffsync
    depends_on: [traefik]
    dns: [8.8.8.8]
    environment: ['PUBLIC_URL=https://sync_ff.andromeda.home/']
    image: sunx/mozilla-syncserver:latest
    labels: [traefik.backend=sync_ff, 'traefik.frontend.rule=Host:sync_ff.${TRAEFIK_DOMAIN}',
      traefik.enable=true, traefik.port=5000]
    networks: [webgateway]
    ports: ['5000:5000']
    volumes: ['${DOCKER_CONFIG}/ffsync:/home/ffsync']
  piwigo:
    container_name: piwigo
    depends_on: [traefik]
    environment: [TZ=Europe/Berlin, PGID=1000, PUID=1000]
    image: linuxserver/piwigo:latest
    labels: [traefik.backend=piwigo, 'traefik.frontend.rule=Host:piwigo.${TRAEFIK_DOMAIN}',
      traefik.enable=true, traefik.port=8760]
    networks: [webgateway]
    ports: ['8760:80']
    volumes: ['${DOCKER_CONFIG}/piwigo:/config']
  portainer:
    container_name: portainer
    depends_on: [traefik]
    image: portainer/portainer
    labels: [traefik.backend=portainer, 'traefik.frontend.rule=Host:portainer.${TRAEFIK_DOMAIN}',
      traefik.enable=true, traefik.port=9000]
    networks: [webgateway]
    ports: ['9000:9000']
    volumes: ['/var/run/docker.sock:/var/run/docker.sock', '/home/kelghar/.portainer:/data']
  pyload:
    container_name: pyload
    depends_on: [traefik]
    environment: ['DOCKUID=${USERMAP_UID}', 'DOCKGID=${USERMAP_GID}']
    image: digrouz/docker-alp-pyload:latest
    labels: [traefik.backend=pyload, 'traefik.frontend.rule=Host:pyload.${TRAEFIK_DOMAIN}',
      traefik.enable=true, traefik.port=8000]
    networks: [webgateway]
    ports: ['7227:7227', '8000:8000', '9666:9666']
    volumes: ['/home/kelghar/mount_point/share/pyload:/downloads', '${DOCKER_CONFIG}/pyload:/config',
      '/etc/localtime:/etc/localtime:ro']
  radicale:
    container_name: radicale
    depends_on: [traefik]
    image: rdissertori/docker-radicale
    labels: [traefik.backend=radicale, 'traefik.frontend.rule=Host:radicale.${TRAEFIK_DOMAIN}',
      traefik.enable=true, traefik.port=5232]
    networks: [webgateway]
    ports: ['5232:5232']
    volumes: ['${DOCKER_CONFIG}/radicale:/data/radicale']
  selfoss:
    container_name: selfoss
    depends_on: [traefik]
    dns: [8.8.8.8]
    environment: ['UID=${USERMAP_UID}', 'GID=${USERMAP_GID}', CRON_PERIOD=15m]
    image: hardware/selfoss
    labels: [traefik.backend=selfoss, 'traefik.frontend.rule=Host:selfoss.${TRAEFIK_DOMAIN}',
      traefik.enable=true, traefik.port=8888]
    networks: [webgateway]
    ports: ['8888:8888']
    volumes: ['${DOCKER_CONFIG}/selfoss:/selfoss/data']
  syncthing:
    container_name: syncthing
    depends_on: [traefik]
    environment: ['PUID=${USERMAP_UID}', 'PGID=${USERMAP_GID}']
    image: linuxserver/syncthing:latest
    labels: [traefik.backend=syncthing, 'traefik.frontend.rule=Host:syncthing.${TRAEFIK_DOMAIN}',
      traefik.enable=true, traefik.port=8384]
    networks: [webgateway]
    ports: ['8384:8384', '22000:22000', '21027:21027/udp']
    volumes: ['${DOCKER_CONFIG}/syncthing:/config', '/home/kelghar/mount_point/share/_syncthing:/sync']
  traefik:
    command: --api --docker --docker.domain=${TRAEFIK_DOMAIN} --logLevel=ERROR
    container_name: traefik
    image: traefik:alpine
    networks: [webgateway]
    ports: ['80:80', '443:443', '8081:8080']
    volumes: ['${DOCKER_CONFIG}/traefik/traefik.toml:/traefik.toml:ro', '/var/run/docker.sock:/var/run/docker.sock',
      '${DOCKER_CONFIG}/traefik/certs:/certs']
  transmission:
    container_name: transmission
    depends_on: [traefik]
    environment: [TZ=Europe/Berlin, 'PUID=${USERMAP_UID}', 'PGID=${USERMAP_GID}']
    image: linuxserver/transmission:latest
    labels: [traefik.backend=transmission, 'traefik.frontend.rule=Host:transmission.${TRAEFIK_DOMAIN}',
      traefik.enable=true, traefik.port=9091]
    networks: [webgateway]
    ports: ['9091:9091', '51413:51413', '51413:51413/udp']
    volumes: ['${DOCKER_CONFIG}/transmission:/config', '/home/kelghar/mount_point/share/_transmission/incoming:/downloads',
      '/home/kelghar/mount_point/share/_transmission/watch:/watch']
version: '3.0'
