services:
  adminer:
    container_name: adminer
    depends_on: [traefik]
    image: clue/adminer
    dns: [8.8.8.8]
    #ports: ['9000:9000']
    labels: [traefik.backend=adminer, 'traefik.frontend.rule=Host:adminer.${TRAEFIK_DOMAIN}',
      traefik.enable=true, traefik.port=80, traefik.docker.network=docker_webgateway]
    networks: [webgateway]
  beets:
    container_name: beets
    environment: [TZ=Europe/Berlin, PGID=1000, PUID=1000]
    image: linuxserver/beets:latest
    ports: ['8337:8337']
    volumes: ['${DOCKER_CONFIG}/beets:/config', '/home/kelghar/mount_point/share/Musik:/music',
      '/home/kelghar/mount_point/share/Import_Musik:/downloads']
  mail:
    container_name: mail
    domainname: andromeda.home
    environment: [ENABLE_SPAMASSASSIN=1, ENABLE_CLAMAV=1, ENABLE_MANAGESIEVE=1, ONE_DIR=1]
    hostname: mail
    image: tvial/docker-mailserver:2.3
    ports: ['25:25', '143:143', '587:587', '993:993', '4190:4190']
    volumes: ['/home/kelghar/.docker-mailserver/maildata:/var/mail', '/home/kelghar/.docker-mailserver/mailstate:/var/mail-state',
      '${DOCKER_CONFIG}/mailserver:/tmp/docker-mailserver/']
  photato:
    container_name: photato
    image: trebonius0/photato:latest
    ports: ['8186:8186']
    volumes: ['${DOCKER_CONFIG}/photato:/config', '/home/kelghar/mount_point/share/_syncthing/Bilder/import:/pictures',
      '/home/kelghar/mount_point/share/_syncthing/Bilder/cache:/cache']
  rainloop:
    container_name: rainloop
    image: solidnerd/rainloop:1.10.5.192
    volumes: ['${DOCKER_CONFIG}/rainloop/data:/var/www/rainloop/data']
    ports: ['5656:80']
   calibre:
        container_name: calibre
            environment: [TZ=Europe/Berlin, PGID=1000, PUID=1000]
            image: linuxserver/calibre-web
            labels: [traefik.backend=calibre, 'traefik.frontend.rule=Host:calibre.${TRAEFIK_DOMAIN}',
              traefik.enable=true, traefik.port=8083]
            networks: [webgateway]
            ports: ['8083:8083']
            volumes: ['${DOCKER_CONFIG}/calibre:/config', '/home/kelghar/mount_point/share/buecher/calibre:/books']
 piwigo:
           container_name: piwigo
            depends_on: [traefik]
             environment: [TZ=Europe/Berlin, PGID=1000, PUID=1000]
              image: linuxserver/piwigo:latest
               labels: [traefik.backend=piwigo, 'traefik.frontend.rule=Host:piwigo.${TRAEFIK_DOMAIN}',
                  traefik.enable=true, traefik.port=80, traefik.docker.network=docker_webgateway]
                 networks: [webgateway]
                  volumes: ['${DOCKER_CONFIG}/piwigo:/config']

version: '3.0'
